@TodoApi_HostAddress = https://localhost:7070

# defines a POST request
POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

GET {{TodoApi_HostAddress}}/todoitems/1

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

PUT {{TodoApi_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/1

###
